# Generated by Django 4.2.7 on 2023-12-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaposts', '0003_alter_media_thumbnail_medium_url_and_more'),
        ('petprofiles', '0004_remove_petprofile_id_alter_petprofile_pet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(default='like', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petprofiles.petprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaposts.post')),
            ],
            options={
                'unique_together': {('pet_profile', 'post')},
            },
        ),
    ]
