# Generated by Django 5.0.1 on 2024-01-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymized_id', models.CharField(max_length=255, unique=True)),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
                ('reason_detail', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
