# Generated by Django 5.0.1 on 2024-01-13 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaposts', '0004_remove_media_thumbnail_medium_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('IC', 'Inappropriate Content'), ('CI', 'Copyright Issue'), ('OT', 'Other')], default='OT', max_length=2)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=500)),
                ('reported_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_posts', to='mediaposts.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reporter', 'reported_post')},
            },
        ),
    ]
