# Generated by Django 5.0.1 on 2024-01-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentreporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcontent',
            name='reason',
            field=models.CharField(choices=[('DL', "I Just Don't Like It"), ('NP', 'Not a Pet Photo'), ('AD', 'Ads'), ('IC', 'Inappropriate Content'), ('CI', 'Copyright Issue'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
