# Generated by Django 5.0.1 on 2024-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentreporting', '0002_alter_reportedcontent_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcontent',
            name='reason',
            field=models.CharField(choices=[('DL', "I Just Don't Like It"), ('NP', 'Not a Pet Photo'), ('SP', 'Self Promotion'), ('IC', 'Inappropriate Content'), ('IP', 'Intellectual Property Violation'), ('VD', 'Violence or Dangerous Organizations'), ('NS', 'Nudity or Sexual Activity'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
