# Generated by Django 4.2.7 on 2023-11-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaposts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='image_url',
            new_name='media_url',
        ),
    ]
