# Generated by Django 4.2.7 on 2023-11-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaposts', '0002_rename_image_url_media_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail_medium_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail_small_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
