# Generated by Django 5.0.2 on 2024-02-26 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaposts', '0004_remove_media_thumbnail_medium_url'),
        ('petprofiles', '0008_alter_petprofile_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='petprofiles.petprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mediaposts.post')),
            ],
        ),
    ]
