# Generated by Django 5.0.2 on 2024-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcomments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
