# Generated by Django 4.2.6 on 2023-10-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petprofiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petprofile',
            old_name='profile_picture',
            new_name='profile_pic_regular',
        ),
    ]
