# Generated by Django 4.2.6 on 2023-10-31 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofiles', '0003_petprofile_profile_pic_thumbnail_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_id',
            field=models.CharField(max_length=63, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Subdomain must be alphanumeric or contain dashes only.', regex='^[a-zA-Z0-9-]+$')]),
        ),
    ]
