# Generated by Django 5.0.1 on 2024-01-24 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofiles', '0006_alter_petprofile_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
