# Generated by Django 5.0.2 on 2024-02-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofiles', '0007_alter_petprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('horse', 'Horse'), ('rabbit', 'Rabbit'), ('turtle', 'Turtle'), ('other', 'Other')], max_length=50),
        ),
    ]
