# Generated by Django 5.0.1 on 2024-01-12 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petprofiles', '0005_alter_petprofile_pet_name'),
        ('userblocking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='display_pet_profile',
            field=models.ForeignKey(blank=True, help_text='The pet profile that was displayed to the blocker when the block was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_display_profile', to='petprofiles.petprofile'),
        ),
    ]
