# Generated by Django 5.0.1 on 2024-01-12 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblocking', '0002_blockeduser_display_pet_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
